namespace UglyToad.PdfPig.DocumentLayoutAnalysis.PageSegmenter
{
    using Content;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A heuristic page segmenter that groups words into lines by baseline proximity and then
    /// groups consecutive lines into blocks based on vertical gaps and font-size transitions.
    /// Heading detection is performed using a font-size histogram to identify the body font size.
    /// </summary>
    public class HeuristicPageSegmenter : IPageSegmenter
    {
        private readonly HeuristicPageSegmenterOptions options;

        /// <summary>
        /// Create an instance of heuristic page segmenter, <see cref="HeuristicPageSegmenter"/>.
        /// </summary>
        public static HeuristicPageSegmenter Instance { get; } = new HeuristicPageSegmenter();

        /// <summary>
        /// Create an instance of heuristic page segmenter using default options values.
        /// </summary>
        public HeuristicPageSegmenter() : this(new HeuristicPageSegmenterOptions())
        {
        }

        /// <summary>
        /// Create an instance of heuristic page segmenter using options values.
        /// </summary>
        /// <param name="options">The <see cref="HeuristicPageSegmenterOptions"/> to use.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public HeuristicPageSegmenter(HeuristicPageSegmenterOptions options)
        {
            this.options = options ?? throw new ArgumentNullException(nameof(options));
        }

        /// <summary>
        /// Get the blocks.
        /// </summary>
        /// <param name="words">The page's words to segment into <see cref="TextBlock"/>s.</param>
        /// <returns>The <see cref="TextBlock"/>s generated by the heuristic method.</returns>
        public IReadOnlyList<TextBlock> GetBlocks(IEnumerable<Word> words)
        {
            if (words?.Any() != true)
            {
                return Array.Empty<TextBlock>();
            }

            var wordList = words.Where(w => !string.IsNullOrWhiteSpace(w.Text)).ToList();
            if (wordList.Count == 0)
            {
                return Array.Empty<TextBlock>();
            }

            // Step 1: Compute font size for each word and determine body font size
            var wordFontSizes = wordList.Select(w => GetWordFontSize(w)).ToList();
            double bodyFontSize = GetBodyFontSize(wordFontSizes);
            double headingThreshold = bodyFontSize * options.HeadingScaleThreshold;

            // Step 2: Compute average letter height for line grouping tolerance
            double avgLetterHeight = wordList
                .SelectMany(w => w.Letters)
                .Select(l => l.BoundingBox.Height)
                .DefaultIfEmpty(0)
                .Average();

            if (avgLetterHeight <= 0)
            {
                avgLetterHeight = 1;
            }

            double lineTolerance = avgLetterHeight * options.LineGapTolerance;

            // Step 3: Group words into lines by baseline Y proximity
            var lines = GroupWordsIntoLines(wordList, wordFontSizes, lineTolerance);

            // Step 4: Sort lines top-to-bottom (descending Y in PDF coords)
            lines.Sort((a, b) => b.BaselineY.CompareTo(a.BaselineY));

            if (lines.Count == 0)
            {
                return Array.Empty<TextBlock>();
            }

            // Step 5: Compute average line height for block gap detection
            double avgLineHeight = lines.Average(l => l.Height);
            if (avgLineHeight <= 0)
            {
                avgLineHeight = 1;
            }

            double blockGapThreshold = avgLineHeight * options.BlockGapMultiplier;

            // Step 6: Group consecutive lines into blocks
            var blocks = new List<TextBlock>();
            var currentBlockLines = new List<LineInfo> { lines[0] };

            for (int i = 1; i < lines.Count; i++)
            {
                double gap = currentBlockLines[currentBlockLines.Count - 1].BaselineY - lines[i].BaselineY;
                bool isLargeGap = gap > blockGapThreshold;
                bool fontSizeChanged = IsHeading(currentBlockLines[currentBlockLines.Count - 1].DominantFontSize, headingThreshold)
                    != IsHeading(lines[i].DominantFontSize, headingThreshold);

                if (isLargeGap || fontSizeChanged)
                {
                    blocks.Add(CreateTextBlock(currentBlockLines));
                    currentBlockLines = new List<LineInfo>();
                }

                currentBlockLines.Add(lines[i]);
            }

            if (currentBlockLines.Count > 0)
            {
                blocks.Add(CreateTextBlock(currentBlockLines));
            }

            return blocks;
        }

        private static double GetWordFontSize(Word word)
        {
            if (word.Letters == null || word.Letters.Count == 0)
            {
                return 0;
            }

            var sizes = word.Letters.Select(l => l.PointSize);
            var mode = sizes.GroupBy(s => s)
                .OrderByDescending(g => g.Count())
                .First()
                .Key;
            return mode;
        }

        private static double GetBodyFontSize(List<double> fontSizes)
        {
            if (fontSizes.Count == 0)
            {
                return 0;
            }

            return fontSizes
                .GroupBy(s => s)
                .OrderByDescending(g => g.Count())
                .First()
                .Key;
        }

        private static bool IsHeading(double fontSize, double headingThreshold)
        {
            return fontSize > headingThreshold;
        }

        private List<LineInfo> GroupWordsIntoLines(List<Word> wordList, List<double> wordFontSizes, double lineTolerance)
        {
            var lines = new List<LineInfo>();
            var assigned = new bool[wordList.Count];

            for (int i = 0; i < wordList.Count; i++)
            {
                if (assigned[i])
                {
                    continue;
                }

                double baselineY = GetBaselineY(wordList[i]);
                var lineWords = new List<(Word Word, double FontSize)>
                {
                    (wordList[i], wordFontSizes[i])
                };
                assigned[i] = true;

                for (int j = i + 1; j < wordList.Count; j++)
                {
                    if (assigned[j])
                    {
                        continue;
                    }

                    double otherBaselineY = GetBaselineY(wordList[j]);
                    if (Math.Abs(baselineY - otherBaselineY) < lineTolerance)
                    {
                        lineWords.Add((wordList[j], wordFontSizes[j]));
                        assigned[j] = true;
                    }
                }

                // Sort words left to right
                lineWords.Sort((a, b) => a.Word.BoundingBox.Left.CompareTo(b.Word.BoundingBox.Left));

                double dominantFontSize = lineWords
                    .Select(w => w.FontSize)
                    .GroupBy(s => s)
                    .OrderByDescending(g => g.Count())
                    .First()
                    .Key;

                double lineHeight = lineWords.Max(w => w.Word.BoundingBox.Height);

                lines.Add(new LineInfo(
                    lineWords.Select(w => w.Word).ToList(),
                    baselineY,
                    lineHeight,
                    dominantFontSize));
            }

            return lines;
        }

        private static double GetBaselineY(Word word)
        {
            if (word.Letters != null && word.Letters.Count > 0)
            {
                return word.Letters[0].StartBaseLine.Y;
            }

            return word.BoundingBox.Bottom;
        }

        private TextBlock CreateTextBlock(List<LineInfo> lineInfos)
        {
            var textLines = lineInfos
                .Select(li => new TextLine(li.Words, options.WordSeparator))
                .ToList();

            return new TextBlock(textLines, options.LineSeparator);
        }

        private sealed class LineInfo
        {
            public IReadOnlyList<Word> Words { get; }
            public double BaselineY { get; }
            public double Height { get; }
            public double DominantFontSize { get; }

            public LineInfo(IReadOnlyList<Word> words, double baselineY, double height, double dominantFontSize)
            {
                Words = words;
                BaselineY = baselineY;
                Height = height;
                DominantFontSize = dominantFontSize;
            }
        }

        /// <summary>
        /// Heuristic page segmenter options.
        /// </summary>
        public class HeuristicPageSegmenterOptions : IPageSegmenterOptions
        {
            /// <summary>
            /// <inheritdoc/>
            /// Default value is -1.
            /// </summary>
            public int MaxDegreeOfParallelism { get; set; } = -1;

            /// <summary>
            /// <inheritdoc/>
            /// <para>Default value is ' ' (space).</para>
            /// </summary>
            public string WordSeparator { get; set; } = " ";

            /// <summary>
            /// <inheritdoc/>
            /// <para>Default value is '\n' (new line).</para>
            /// </summary>
            public string LineSeparator { get; set; } = "\n";

            /// <summary>
            /// The font size ratio above body font size to classify a word as a heading.
            /// <para>Default value is 1.2.</para>
            /// </summary>
            public double HeadingScaleThreshold { get; set; } = 1.2;

            /// <summary>
            /// The vertical gap tolerance for same-line grouping, relative to average letter height.
            /// <para>Default value is 0.5.</para>
            /// </summary>
            public double LineGapTolerance { get; set; } = 0.5;

            /// <summary>
            /// The gap multiplier for block boundary detection, relative to average line height.
            /// <para>Default value is 1.5.</para>
            /// </summary>
            public double BlockGapMultiplier { get; set; } = 1.5;
        }
    }
}
